[project]
name = "libspec"
version = "0.1.0"
description = "Spec-driven development library"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
]

[build-system]
requires = ["setuptools>=65.5.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv.workspace]
members = [
    ".",  # the root (libspec package)
    "examples/temperature-conversion",
    "examples/tictactoe-urwid/groq",
    "examples/tictactoe-urwid/claude",
]

[dependency-groups]
dev = [
    "pudb>=2025.1.5",
    "pytest>=9.0.2",
]

